
spring:
  application:
    name: "My Spring Boot app"

  datasource:
    username: myuser
    password: secret
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/mydb
    driver-class-name: com.mysql.cj.jdbc.Driver

management:
  info:
    env:
      enabled: true

  endpoint:
    health:
      show-details: always
      show-components: always

  endpoints:
    web:
      exposure:
        include: health, info

info:
  application:
    name: ${spring.application.name}
    description: My very cool Spring Boot application
    version: '@project.version@'
    spring-boot-version: '@project.parent.version@'

